COP4710/COP4710/Controllers/AdminMenuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace COP4710.Controllers
{
    public class AdminMenuController : Controller
    {
        //
        // GET: /AdminMenu/

        public ActionResult Users()
        {
            return View();
        }

        public ActionResult Dispatches()
        {
            return View();
        }


        public ActionResult Reports()
        {
            return View();
        }

        public ActionResult Menu()
        {
            return View();
        }
    }
}

COP4710/COP4710/Controllers/SharedController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace COP4710.Controllers
{
    public class SharedController : Controller
    {
        //
        // GET: /Shared/



        public ActionResult Index()
        {
            return View();
        }

    }
}

COP4710/COP4710/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/Site.css")" type="text/css" rel="Stylesheet" />
    <link href="@Url.Content("~/Content/toggle.css")" type="text/css" rel="Stylesheet" />
    <link href="@Url.Content("~/Content/themes/black-tie/jquery-ui-1.8.16.css")" type="text/css" rel="Stylesheet" />
    <script src="@Url.Content("~/Scripts/jquery-1.5.1.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery-ui-1.8.11.min.js")" type="text/javascript"></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/jquery.scrollTo-min.js")"></script>
    <script src="@Url.Content("~/Scripts/jquery.localscroll-1.2.7-min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/Site.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/toggle.js")" type="text/javascript"></script>
    <script type="text/javascript">
    var _imgDir = "@Url.Content("~/Content/Images/")";
    </script>
</head>
<body>
    <div id="main">
        <div class="Header">
            <div class="PageTitle">
                @ViewBag.PageTitle
            </div>
            <div style="float: right; display: inline; margin-top:8px">
                @{Html.RenderAction("AccountBar", "Account", new { });}
            </div>

           
                @{Html.RenderAction("Menu", "AdminMenu");}
           
        </div>
        <hr id="pageSeperator" />
        <div >
            @RenderBody()
        </div>
        <div id="footer">
        </div>
    </div>
</body>
</html>

COP4710/COP4710/Views/Shared/_LogOnPartial.cshtml
@if(Request.IsAuthenticated) {
    <text>Welcome <strong>@User.Identity.Name</strong>!
    [ @Html.ActionLink("Log Off", "LogOff", "Account") ]</text>
}
else {
    @:[ @Html.ActionLink("Log On", "LogOn", "Account") ]
}