COP4710/COP4710/Controllers/AdminMenuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace COP4710.Controllers
{
    public class AdminMenuController : Controller
    {
        //
        // GET: /AdminMenu/

        public ActionResult Users()
        {
            return View();
        }

        public ActionResult Dispatches()
        {
            return View();
        }


        public ActionResult Reports()
        {
            return View();
        }

        public ActionResult Menu()
        {
            return View();
        }
    }
}

COP4710/COP4710/Controllers/ReportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using COP4710.DataAccess;
using COP4710.Services;
using COP4710.Models;
using ExcelLibrary;

namespace COP4710.Controllers
{
    public class ReportController : Controller
    {
        //
        // GET: /Report/

        public ActionResult Index()
        {
            return RedirectToAction("Import");
        }

        [HttpPost]
        public ActionResult Import(HttpPostedFileBase file)
        {

            if (file.ContentLength > 0)
            {
                var fileName = Path.GetFileName(file.FileName);
                var path = Path.Combine(Server.MapPath("~/App_Data/uploads"), fileName);
                file.SaveAs(path);

                new ExcelService().ImportFromExcel(path, (UserModel)Session["CurrentUser"]);
            }

            return RedirectToAction("Index");
        }

        public ActionResult Import()
        {
            return View();
        }

        public ActionResult Export()
        {
            return View(new ReportModel() { StartDate = DateTime.Today.AddYears(-1), EndAge = 200, StartAge = 0, EndDate = DateTime.Today });
        }

        [HttpPost]
        public ActionResult Export(FormCollection collection)
        {
            ReportModel model = new ReportModel();

            TryUpdateModel<ReportModel>(model, collection.ToValueProvider());



            string filename = Server.MapPath("~/app_data/Reports/Report_" + DateTime.Today.ToString("MMddyyyy") + ".xls");
            string contentType = "application/vnd.ms-excel";

            ExcelLibrary.DataSetHelper.CreateWorkbook(filename, ReportDAO.ExecuteReport(model));

            if (System.IO.File.Exists(filename))
            {
                return File(new FileStream(filename, FileMode.Open), contentType, filename);
            }

            return View(model);
        }

    }
}

COP4710/COP4710/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using COP4710.Models;
using COP4710.Models.Enumerations;
using COP4710.DataAccess;
using COP4710.Attributes;

namespace COP4710.Controllers
{
    [Authorization(UserRole = AccountType.Administrator)]
    public class UserController : Controller
    {
        //
        // GET: /User/

        public ActionResult Index()
        {
            return View(UserDAO.ListUsers());
        }

        //
        // GET: /User/Details/5

        public ActionResult Details(string id)
        {
            return View(UserDAO.GetUserByUsername(id));
        }

        //
        // GET: /User/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /User/Create

        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                UserModel user = new UserModel();

                TryUpdateModel<UserModel>(user, collection.ToValueProvider());

                UserDAO.Insert(user);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /User/Edit/5

        public ActionResult Edit(string id)
        {
            return View(UserDAO.GetUserByUsername(id));
        }

        //
        // POST: /User/Edit/5

        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                UserModel user = new UserModel();
                TryUpdateModel(user, collection.ToValueProvider());

                UserDAO.Update(user);

                return RedirectToAction("Details", new { id = id });
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /User/Delete/5

        public ActionResult Delete(int id)
        {
            return View();
        }

        //
        // POST: /User/Delete/5

        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public List<SelectListItem> AjaxListUsersByName()
        {

            List<UserModel> users = UserDAO.ListUsers();
            List<SelectListItem> userItems = new List<SelectListItem>();

            users.ForEach(delegate(UserModel user)
            {
                userItems.Add(new SelectListItem() { Text = user.FirstName + " " + user.LastName, Value = user.UserName });
            });

            return userItems;
        }
    }
}

COP4710/COP4710/Views/AdminMenu/Dispatches.cshtml
@{
    Layout = null;
}

    <div class="MenuItem" id="Reports">
            @Html.ActionLink("Dispatch", "Index", "Dispatch", null, new { })
    </div>

COP4710/COP4710/Views/AdminMenu/Menu.cshtml
@{
    Layout = null;
}
@using COP4710.Models;
@using COP4710.Models.Enumerations;
<!DOCTYPE html>
@if (Session["CurrentUser"] != null && ((UserModel)Session["CurrentUser"]).AccountType == AccountType.Administrator)
{<div style="display: inline-block;">
    <div style="display: block;">
        <div class="MenuItem" id="Users">
            @Html.ActionLink("Users", "Index", "User", null, new { })
        </div>
        <div class="MenuItem" id="Forms">
            @Html.ActionLink("Forms", "Index", "Dispatch", null, new { })
        </div>
        <div class="MenuItem" id="Reports">
            @Html.ActionLink("Reports", "Index", "Report", null, new { })
        </div>
    </div>
    </div>
}

COP4710/COP4710/Views/AdminMenu/Reports.cshtml
@{
    Layout = null;
}

    <div class="MenuItem" id="Reports">
            @Html.ActionLink("Reports", "Index", "Reports", null, new { })
    </div>

COP4710/COP4710/Views/AdminMenu/Users.cshtml
@{
    Layout = null;
}
@using COP4710.Models;
@using COP4710.Models.Enumerations;

@if (Session["CurrentUser"] != null && ((UserModel)Session["CurrentUser"]).AccountType == AccountType.Administrator)
{
    <div class="MenuItem" id="Users">
            @Html.ActionLink("Users", "Index", "User", null, new {})
    </div>
}