COP4710/COP4710/Controllers/DispatchController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using COP4710.Models;
using COP4710.Models.Enumerations;
using COP4710.DataAccess;
using COP4710.Attributes;

namespace COP4710.Controllers
{
    [Authorization]
    public class DispatchController : Controller
    {
        //
        // GET: /Dispatch/

        public ActionResult Index(int? page)
        {
            if (page.HasValue)
            {
                ViewBag.Page = page;
                return View(DispatchDAO.List(page.Value));
            }
            else
            {
                ViewBag.Page = page;
                Boolean disablePaging = false;
                Boolean.TryParse(ConfigurationManager.AppSettings["DisablePaging"].ToString(), out disablePaging);

                if (disablePaging == false)
                    return RedirectToAction("Index", new { @page = 0 });
                else
                    return View(DispatchDAO.List());
            }
        }




        //
        // GET: /Dispatch/Details/5

        public ActionResult Details(int id)
        {
            DispatchModel dispatch = DispatchDAO.GetDispatchByID(id);

            if (dispatch != null)
                return View(dispatch);
            else
                return RedirectToAction("index");
        }

        //
        // GET: /Dispatch/Create

        public ActionResult Create()
        {
            return View(new DispatchModel());
        }

        //
        // POST: /Dispatch/Create

        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                DispatchModel form = new DispatchModel();

                TryUpdateModel<DispatchModel>(form, collection.ToValueProvider());

                int rowsAffected = DispatchDAO.Insert(form);

                return RedirectToAction("Index");

            }
            catch
            {
                return RedirectToAction("Create");
            }
        }

        //
        // GET: /Dispatch/Edit/5

        [Authorization(UserRole = AccountType.Administrator)]
        public ActionResult Edit(int id)
        {
            if (id > 0)
                return View(DispatchDAO.GetDispatchByID(id));
            else
                return RedirectToAction("Index");
        }

        //
        // POST: /Dispatch/Edit/5


        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            DispatchModel form = new DispatchModel();

            try
            {

                TryUpdateModel<DispatchModel>(form, collection.ToValueProvider());

                int rowsAffected = DispatchDAO.UpdateForm(form);
            }
            catch
            {
                return View();
            }

            try
            {
                return RedirectToAction("Edit", new { id = form.FormID });
            }
            catch
            {
                return RedirectToAction("Index");
            }

        }



        public List<SelectListItem> ListETA()
        {
            List<SelectListItem> list = new List<SelectListItem>();

            for (int i = 0; i <= 60; i++)
            {
                list.Add(new SelectListItem() { Text = i.ToString(), Value = i.ToString() });
            }

            return list;
        }
    }
}

COP4710/COP4710/Views/Dispatch/Create.cshtml
@model COP4710.Models.DispatchModel
@using COP4710.Extensions;
@using COP4710.Controllers;
@{
    ViewBag.Title = "New Dispatch";
    ViewBag.PageTitle = ViewBag.Title;
}
@using (Html.BeginForm())
{
    @Html.ValidationSummary()

    <div class="Main" id="Main">
        <div class="Sidebar" id="sidebar">
            @Html.ActionLink("<< Forms", "Index", "Dispatch", null, new { @class = "Submit", @ID = "Back" })
            <ul id="sidebarLinks">
            </ul>
            <hr />
            <input type="submit" id="Submit" title="Submit" value="Submit" />
        </div>
        <div class="Content" id="content">
            @{
                Html.RenderPartial("Form", Model);
            }
        </div>
    </div>
}
<script type="text/javascript">

    $(function () {


        $('input, select, textarea').focus(function () {
            focusElement(this);
        });

        $('input, select, textarea').click(function () {
            focusElement(this);
        });

    });

    function focusElement(elem) {

        $('.focused').removeClass('focused');
        $(elem).addClass('focused');
    }
</script>

COP4710/COP4710/Views/Dispatch/Edit.cshtml
@model COP4710.Models.DispatchModel
@using COP4710.Extensions;
@using COP4710.Controllers;
@{
    ViewBag.Title = "Dispatch Form Edit";
    ViewBag.PageTitle = "Edit Form - " + Model.FormID;
}
@using (Html.BeginForm())
{
    @Html.ValidationSummary()

    <div class="Main" id="Main">
        <div class="Sidebar" id="sidebar">
            @Html.ActionLink("<< Detail", "Details", "Dispatch", new { id = Model.FormID }, new { @class = "Submit", @ID = "Back" })
            <ul id="sidebarLinks">
            </ul>
            <hr />
            <input type="submit" id="Submit" title="Update" value="Update" />
        </div>
        <div class="Content" id="content">
              @{
                Html.RenderPartial("Form", Model);
            }
        </div>
    </div>
}
<script type="text/javascript">

</script>

COP4710/COP4710/Views/Dispatch/Form.cshtml
@model COP4710.Models.DispatchModel
@using COP4710.Extensions;
@using COP4710.Controllers;
@{
    ViewBag.Title = "New Dispatch";
    ViewBag.PageTitle = ViewBag.Title;
}
@using (Html.BeginForm())
{
    @Html.ValidationSummary()

    <div id="GeneralInfo" class="Section" linktext="General Info">
        <div class="Header">
            General Information
        </div>
        <div class="Field">
            <div class="Label">
                Date
            </div>
            <div class="Input">
                @Model.CreateDate.ToString("hh:mm tt MM/dd/yyyy")
                @Html.HiddenFor(m => m.FormID)
            </div>
        </div>
        <div class="Field">
            <div class="Label"> 
                County
            </div>
            <div class="Input">
                @Html.DropDownListFor(x => x.County, new SelectList(Enum.GetValues(typeof(COP4710.Models.Enumerations.County))))
            </div>
        </div>
        <div class="Field">
            <div class="Label">
                Unit #
            </div>
            <div class="Input">
                @Html.TextBoxFor(m => m.Unit)
                @Html.ValidationMessageFor(m => m.Unit, "Oh No", new { @style = "Display:none;" })
            </div>
        </div>
    </div>
    <div id="ComplainantInfo" class="Section" linktext="Complainant Info">
        <div class="Header">
            Complainant Information
        </div>
        <div class="Field">
            <div class="Label">
                Age
            </div>
            <div class="Input">
                @Html.TextBoxFor(m => m.InitialCondition.Age)@Html.DropDownListFor(x => x.InitialCondition.AgeType, new SelectList(Enum.GetValues(typeof(COP4710.Models.Enumerations.AgeType))))
            </div>
        </div>
        <div class="Field">
            <div class="Label">
                Sex
            </div>
            <div class="Input">
                @Html.DropDownListFor(x => x.InitialCondition.Gender, new SelectList(Enum.GetValues(typeof(COP4710.Models.Enumerations.Gender))))
            </div>
        </div>
        <div class="Field">
            <div class="Label">
                A&O X
            </div>
            <div class="Input">
                @Html.TextBoxFor(m => m.InitialCondition.A_OX, new { @class = "textbox" });
            </div>
        </div>
        <div class="Field">
            <div class="Label">
                Category
            </div>
            <div class="Input">
                @Html.DropDownListFor(x => x.InitialCondition.Category, new SelectList(Enum.GetValues(typeof(COP4710.Models.Enumerations.Category))))
            </div>
        </div>
        <div class="Field">
            <div class="Label">
                Chief Complaint
            </div>
            <div class="Input">
                @Html.TextAreaFor(m => m.InitialCondition.ChiefComplaint, new { @class = "textbox" })
            </div>
        </div>
        <div class="Field">
            <div class="Label">
                Blood Pressure
            </div>
            <div class="Input">
                @Html.TextBoxFor(m => m.InitialCondition.BP1.Systolic, new { @class = "BP" })
                /
                @Html.TextBoxFor(m => m.InitialCondition.BP1.Diastolic, new { @class = "BP" })
            </div>
            <span class="Seperator">|</span>
            <div class="Input">
                @Html.TextBoxFor(m => m.InitialCondition.BP2.Systolic, new { @class = "BP" })
                /
                @Html.TextBoxFor(m => m.InitialCondition.BP2.Diastolic, new { @class = "BP" })
            </div>
        </div>
        <div class="Field">
            <div class="Label">
                Pulse
            </div>
            <div class="Input">
                @Html.TextBoxFor(m => m.InitialCondition.Pulse1, new { @class = "textbox short" })
                <span class="Seperator">|</span>
                @Html.TextBoxFor(m => m.InitialCondition.Pulse2, new { @class = "textbox short" })
            </div>
        </div>
        <div class="Field">
            <div class="Label">
                Respirations
            </div>
            <div class="Input">
                @Html.TextBoxFor(m => m.InitialCondition.Resp1, new { @class = "textbox short" })
                <span class="Seperator">|</span>
                @Html.TextBoxFor(m => m.InitialCondition.Resp2, new { @class = "textbox short" })
            </div>
        </div>
        <div class="Field">
            <div class="Label">
                O2 Saturation
            </div>
            <div class="Input">
                @Html.TextBoxFor(m => m.InitialCondition.O2Sat, new { @class = "textbox short" })%
                <span class="Seperator">|</span>
                @Html.TextBoxFor(m => m.InitialCondition.O2Sat2, new { @class = "textbox short" })%
            </div>
        </div>
    </div>
    <div id="CrashInfo" class="Section" linktext="Crash Info">
        <div class="Header">
            Crash Information
        </div>
        <div class="Field">
            <div class="Label">
                Driver
            </div>
            <div class="Input">
                @Html.DropDownListFor(x => x.CrashInformation.DriverRestrained, new SelectList(Enum.GetNames(typeof(COP4710.Models.Enumerations.DriverRestraintLevel))))
            </div>
        </div>
        <div class="Field">
            <div class="Label">
                Passeneger
            </div>
            <div class="Input">
                @Html.DropDownListFor(x => x.CrashInformation.PassengerRestrained, new SelectList(Enum.GetValues(typeof(COP4710.Models.Enumerations.PassengerRestraintLevel))))
            </div>
        </div>
        <div class="Field">
            <div class="Label">
                Speed
            </div>
            <div class="Input">
                <input class="textbox" />
            </div>
        </div>
        <div class="Field" style="">
            <div class="Label">
                Condition
            </div>
            <div class="Input">
                <div class="Checklist" style="width: 400px">
                    <table>
                        <tr>
                            <td class="selectable">
                                @Html.CheckBoxFor(m => m.CrashInformation.Ejected) @Html.LabelFor(m => m.CrashInformation.Ejected)
                            </td>
                            <td class="selectable">
                                @Html.CheckBoxFor(m => m.CrashInformation.Entrapped) @Html.LabelFor(m => m.CrashInformation.Entrapped)
                            </td>
                        </tr>
                        <tr>
                            <td class="selectable">
                                @Html.CheckBoxFor(m => m.CrashInformation.Rollover) @Html.LabelFor(m => m.CrashInformation.Rollover)
                            </td>
                            <td class="selectable">
                                @Html.CheckBoxFor(m => m.CrashInformation.HasHelmet) @Html.LabelFor(m => m.CrashInformation.HasHelmet)
                            </td>
                        </tr>
                        <tr>
                            <td class="selectable">
                                @Html.CheckBoxFor(m => m.CrashInformation.AirbagDeployed) @Html.LabelFor(m => m.CrashInformation.AirbagDeployed)
                            </td>
                            <td class="selectable">
                                @Html.CheckBoxFor(m => m.CrashInformation.isPackaged) @Html.LabelFor(m => m.CrashInformation.isPackaged)
                            </td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <div id="Alerts" class="Section" linktext="Alerts">
        <div class="Header">
            Alerts
        </div>
        <div class="Field">
            <div class="Label">
                @Html.LabelFor(m => m.Alerts.TraumaAlert)
            </div>
            <div class="Input">
                @Html.CheckBoxFor(m => m.Alerts.TraumaAlert)
            </div>
        </div>
        <div class="Field">
            <div class="Label">
                @Html.LabelFor(m => m.Alerts.StrokeAlert)
            </div>
            <div class="Input">
                @Html.CheckBoxFor(m => m.Alerts.StrokeAlert)
            </div>
        </div>
        <div class="Field">
            <div class="Label">
                @Html.LabelFor(m => m.Alerts.onSet)
            </div>
            <div class="Input">
                @Html.TextBoxFor(m => m.Alerts.onSet);
            </div>
        </div>
        <div class="Field">
            <div class="Label">
                @Html.LabelFor(m => m.Alerts.STEMI)
            </div>
            <div class="Input">
                @Html.CheckBoxFor(m => m.Alerts.STEMI)
            </div>
        </div>
        <div class="Field">
            <div class="Label">
                @Html.LabelFor(m => m.Alerts.TIBR)
            </div>
            <div class="Input">
                @Html.TextBoxFor(m => m.Alerts.TIBR)
            </div>
        </div>
        <div class="Field">
            <div class="Label">
                @Html.LabelFor(m => m.Alerts.History)
            </div>
            <div class="Input">
                @Html.DropDownListFor(x => x.Alerts.History, new SelectList(Enum.GetValues(typeof(COP4710.Models.Enumerations.History))))
            </div>
        </div>
        <div class="Field">
            <div class="Label">
                @Html.LabelFor(m => m.Alerts.Treatment)
            </div>
            <div class="Input">
                @Html.DropDownListFor(x => x.Alerts.Treatment, new SelectList(Enum.GetValues(typeof(COP4710.Models.Enumerations.Treatment))))
            </div>
        </div>
        <div class="Field">
            <div class="Label">
                @Html.LabelFor(m => m.Alerts.DISP)
            </div>
            <div class="Input">
                @Html.DropDownListFor(m => m.Alerts.DISP, new UserController().AjaxListUsersByName())
            </div>
        </div>
        <div class="Field">
            <div class="Label">
                @Html.LabelFor(m => m.Alerts.Notified)
            </div>
            <div class="Input">
                @Html.TextBoxFor(m => m.Alerts.Notified)
            </div>
        </div>
        <div class="Field">
            <div class="Label">
                @Html.LabelFor(m => m.Alerts.ETA)
            </div>
            <div class="Input">
                @Html.DropDownListFor(m => m.Alerts.ETA, new DispatchController().ListETA())
            </div>
        </div>
    </div>
    <div id="MedicalDetail" class="Section" linktext="Medical Detail">
        <div class="Header">
            Medical Details
        </div>
        <div class="Field">
            <div class="Label">
                @Html.LabelFor(m => m.MedicalDetail.Detail)
            </div>
            <div class="Input">
                @Html.TextAreaFor(m => m.MedicalDetail.Detail, new { @class = "textbox" })
            </div>
        </div>
        <div class="Field">
            <div class="Label">
                @Html.LabelFor(m => m.MedicalDetail.Level)
            </div>
            <div class="Input">
                @Html.TextBoxFor(m => m.MedicalDetail.Level)
            </div>
        </div>
        <div class="Field">
            <div class="Label">
                @Html.LabelFor(m => m.MedicalDetail.TC_ER__PEDS)
            </div>
            <div class="Input">
                @Html.DropDownListFor(x => x.MedicalDetail.TC_ER__PEDS, new SelectList(Enum.GetValues(typeof(COP4710.Models.Enumerations.DispatchDestination))))
            </div>
        </div>
    </div>
    <div id="MedicalControl" class="Section" linktext="Medical Control">
        <div class="Header">
            Medical Controls
        </div>
        <div class="Field">
            <div class="Label">
                @Html.LabelFor(m => m.MedicalControl.Rescue)
            </div>
            <div class="Input">
                @Html.TextBoxFor(m => m.MedicalControl.Rescue)
            </div>
        </div>
        <div class="Field">
            <div class="Label">
                @Html.LabelFor(m => m.MedicalControl.Meds)
            </div>
            <div class="Input">
                @Html.TextBoxFor(m => m.MedicalControl.Meds)
            </div>
        </div>
        <div class="Field">
            <div class="Label">
                @Html.LabelFor(m => m.MedicalControl.DrsSignature)
            </div>
            <div class="Input">
                @Html.TextBoxFor(m => m.MedicalControl.DrsSignature)
            </div>
        </div>
        <div class="Field">
            <div class="Label">
                @Html.LabelFor(m => m.MedicalControl.DEANumber)
            </div>
            <div class="Input">
                @Html.TextBoxFor(m => m.MedicalControl.DEANumber)
            </div>
        </div>
        <div class="Field">
            <div class="Label">
                @Html.LabelFor(m => m.MedicalControl.NARC)
            </div>
            <div class="Input">
                @Html.TextBoxFor(m => m.MedicalControl.NARC)
                @{ 
           Html.ValidateFor(m => m.MedicalControl.NARC);
                }
            </div>
        </div>
    </div>
}

COP4710/COP4710/Views/Dispatch/Index.cshtml
@model IEnumerable<COP4710.Models.DispatchModel>
@using COP4710.Models;
@{
    ViewBag.Title = "Dispatch Forms";
    ViewBag.PageTitle = "Dispatch Forms";
    
}
<div id="sidebar" class="fixed">
    <a href="@Url.Action("Create")" class="Submit">New Form</a>
</div>
<div class="Content">
    <div class="Section">
        <div class="Field">
            <div class="Label" style="display:inline; vertical-align:middle;" >
                Go to form
            
                <input type="text" id="gotoForm" style="padding:0; margin:0; width:5em;"/>
                <a id="goButton" class="Submit Small">Go </a>
            </div>
        </div>

        @foreach (DispatchModel item in Model)
        {
            <a href="@Url.Action("Details", new { id = item.FormID })" style="display:block; margin-right:20px;" >
                <div class="ListItem">
                    <div class="left">
                        Form @item.FormID</div>
                    <div class="right">@item.CreateDate.ToString("hh:mm tt MM/dd/yyyy")</div>
                </div>
            </a> 
        }
        <div class="Pager">
            <hr />
            @if ((int)ViewBag.Page > 0)
            {
                @Html.ActionLink("Prev", "Index", new { Page = ViewBag.Page - 1 }, new { @class = "Submit" })   
            }
            &nbsp;
            @Html.ActionLink("Next", "Index", new { Page = (int)ViewBag.Page + 1 }, new { @class = "Submit" })
        </div>
    </div>
</div>
<script type="text/javascript">

    var _dispatchDetail = "@Url.Action("Details")/";
    $(function () {
        $('#gotoForm').keyup(function () {

            var value = $('#gotoForm').val().replace(/^\s\s*/, '').replace(/\s\s*$/, '');
            var intRegex = /^\d+$/;

            if (intRegex.test(value)) {
                $('#goButton').attr('href', _dispatchDetail + value).removeClass('disabled');

            }
            else {
               $('#goButton').attr('href', '#').addClass('disabled');
            }

        });
    });
</script>